if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS "13.0")
        message(FATAL_ERROR "alt requires GCC 13 or later (found ${CMAKE_CXX_COMPILER_VERSION})")
    endif()
elseif(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
    if(CMAKE_CXX_COMPILER_VERSION VERSION_LESS "17.0")
        message(FATAL_ERROR "alt requires Clang 17 or later (found ${CMAKE_CXX_COMPILER_VERSION})")
    endif()
else()
    message(FATAL_ERROR "alt only supports GCC and Clang (found ${CMAKE_CXX_COMPILER_ID})")
endif()
